version: '3.8'
services:
    gradle:
        image: gradle:7.1.1-jdk11
        command: >
            sh -c "cd /Octopus &&
            ./gradlew clean distZip &&
            chmod 777 /Octopus/build/distributions/* && 
            cp /Octopus/build/distributions/*.zip /Octopus/docker_data/teamcity-server/datadir/plugins"
        volumes:
            - ./:/Octopus